version: "3.9"

services:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: ${PROJECT_NAME:-monitoring}-cadvisor
    privileged: true
    ports:
     - "${CADVISOR_PORT:-8181}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    user: root
    networks:
      - monitoring_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ${PROJECT_NAME:-monitoring}-node_exporter
    pid: "host"
    ports:
      - "${NODE_EXPORTER_PORT:-9100}:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped
    networks:
      - monitoring_network

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: ${PROJECT_NAME:-monitoring}-nginx_exporter
    ports:
      - "${NGINX_EXPORTER_PORT:-9113}:9113"
    command:
      - "--nginx.scrape-uri=http://host.docker.internal/status"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - monitoring_network

#  apache_exporter:
#    image: bitnami/apache-exporter:latest
#    container_name: ${PROJECT_NAME:-monitoring}-apache_exporter
#    ports:
#      - "${APACHE_EXPORTER_PORT:-9117}:9117"
#    command:
#      - '--scrape_uri=http://host.docker.internal/server-status?auto'
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    restart: unless-stopped
#    networks:
#      - monitoring_network

  promtail:
    image: grafana/promtail:latest
    container_name: ${PROJECT_NAME:-monitoring}-promtail
    ports:
      - "${PROMTAIL_PORT:-9080}:9080"
    volumes:
      - /var/log:/var/log
      - /etc/promtail:/etc/promtail
    command:
      - --config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge
