server {
    listen 80;
    server_name localhost;

    location /status {
        stub_status;
        allow 127.0.0.1;
        allow <docker network subnet;   # Allow MONITORING_DOCKER_NETWORK_SUBNET
        deny all;
    }
}
